### ISSUE TITLE
jq@1.0.0 import fails

### ISSUE THREAD

**Issue by timhudson** [importpw/yq#1]
[`jq@1.0.0`](https://github.com/importpw/jq/commit/8eaa266f5b107b1a0ceb7baad13edba99bf62b35) is not tagged which results in a failed import of `yq@1.1.0`.

----

`test-import.sh`

``` sh
#!/usr/bin/env import
import yq@1.1.0
```

```
$ ./test-import
curl: (22) The requested URL returned error: 404 Not Found
import: failed to download: https://import.pw/jq@1.0.0
```

**Comment by styfle** [comment]
@TooTallNate I think that yq needs to import jq before it can be used.

When I run `db`, I get the following error:

> /Users/styfle/.import-cache/links/https://import.pw/yq@1.0.0: line 4: jq: command not found

**Comment by TooTallNate** [comment]
Shoot, sorry about that! I pushed the tag, should be all good now.
